### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by object-Object** [object-Object/HexDebug#2]
- [ ] Allow debug client to fetch sources after termination (ie. for exceptions).
- [ ] Add a cool sound effect!
- [ ] Implement the Splicing Table.
- [ ] Add configs:
  - [ ] Disable opening local port.
  - [ ] Disable smart shift-scroll for debugger when not debugging.
- [ ] Support debugging circles.
- [ ] Support debugging wisps.
